### ISSUE TITLE
Stop removing evos licencing headers from this mode switch and it's it's corresponding tile

### ISSUE THREAD

**Issue by AnierinBliss** [cjh1249131356/bliss_device_oneplus_sm8250-common#1]
https://github.com/cjh1249131356/bliss_device_oneplus_sm8250-common/blob/f9f0fcdea07de3d2f2108fce2997fe5999992940/DeviceSettings/src/org/bliss/device/DeviceSettings/ModeSwitch/GameModeSwitch.java#L2

https://github.com/Evolution-X-Devices/hardware_oneplus/blob/9a7b7bd04e2844aacc5925008d91d668b2313f80/DeviceExtras/src/org/evolution/device/DeviceExtras/ModeSwitch/GameModeSwitch.java#L3

**Comment by AnierinBliss** [comment]
It seems to be a rather common occurrence for you two to either A. Remove my signatures, or B. Completely disregard authorship and proceed to remove licencing headers from files you kang.

**Comment by cjh1249131356** [comment]
1. It's a copy paste of Omni's dc-dimming switch, with just node and res change, don't you think it's not appropriate to add a license to it?
2. Please check clearly, I'm not using same implementation from yours.  https://github.com/cjh1249131356/bliss_device_oneplus_sm8250-common/blob/f9f0fcdea07de3d2f2108fce2997fe5999992940/DeviceSettings/src/org/bliss/device/DeviceSettings/DeviceSettings.java#L305.
3. Who stole Omni's DeviceSettings and give credits to himself? Who picked commits from our side and squashed them to keep himself main author?
Moreover, check these
https://github.com/Evolution-X-Devices/device_oneplus_sm8250-common/commit/8c9d86bda942d876f54df5fddf1f42b332bae21a
https://github.com/PixelExperience-Devices/device_oneplus_sm8250-common/commit/b2d1bcb921a3ab0f522d5c83cfbaa73c6033acf1#diff-5dfb63294faa0dc5eb17081c1f8b21c4adf7b2822997fa336ea479e789514cd9R6
How one can come and making dramas while himself is kanging stuff?

**Comment by AnierinBliss** [comment]
Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones you are kanging my commit, which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the as the selinux policy you've linked, I solved that myself after encountering the error during build time

**Comment by AnierinBliss** [comment]
You guys took my commit, rebranded it, moved me under your guys name in the co authored section and called it a day. That's disrespectful git practice and you outta be ashamed of yourselves.

**Comment by cjh1249131356** [comment]
> Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones who are kanging my commit.. which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the selinux policy you've linked, I solved that myself after encountering the error during build time so it's not a kang, lol?

Code refactor & Clean up, lol, I wonder how little thing you did comparing to original DeviceSettings. Anyone can do a comparation if they want.

**Comment by AnierinBliss** [comment]
> > Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones who are kanging my commit.. which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the selinux policy you've linked, I solved that myself after encountering the error during build time so it's not a kang, lol?
> 
> Code refactor & Clean up, lol, I wonder how little thing you did comparing to original DeviceSettings. Anyone can do a comparation if they want.

Whatever your stance is on how much I did, x, y and Z is irrelevant. I put the commit together, and it should be updated to reflect such.

**Comment by cjh1249131356** [comment]
> > > Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones who are kanging my commit.. which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the selinux policy you've linked, I solved that myself after encountering the error during build time so it's not a kang, lol?
> > 
> > 
> > Code refactor & Clean up, lol, I wonder how little thing you did comparing to original DeviceSettings. Anyone can do a comparation if they want.
> 
> Whatever your stance is on how much I did, x, y and Z is irrelevant. I put the commit together, and it should be updated to reflect such.

Oh, if you saying so, who came to spam and call Chandu kanger while he is doing same squash thing?

**Comment by cjh1249131356** [comment]
We picked from Omni, how you saying we are kanging yours? And the fact is you did little thing in DeviceSettings, keep searching and spaming if they are not following you lol. Anyway I don't want to waste time on this.

**Comment by AnierinBliss** [comment]
> > > > Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones who are kanging my commit.. which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the selinux policy you've linked, I solved that myself after encountering the error during build time so it's not a kang, lol?
> > > 
> > > 
> > > Code refactor & Clean up, lol, I wonder how little thing you did comparing to original DeviceSettings. Anyone can do a comparation if they want.
> > 
> > 
> > Whatever your stance is on how much I did, x, y and Z is irrelevant. I put the commit together, and it should be updated to reflect such.
> 
> Oh, if you saying so, who came to spam and call Chandu kanger while he is doing same squash thing?

Squashing isn't kanging. In fact, I have a list of commit to commit shit that Chandu picked from me, removed my signatures from and tried to pull it off to the community as if he found them himself, etc. It's pretty ironic you guys can't take accountability for anything but defend yourselves to no end despite being in the wrong.

**Comment by cjh1249131356** [comment]
> > > > > Oh so you're assuming I copied Omni although I've actually been refactoring the entire application for about 2 years now, adding various features and cleaning up the code the way I see fit? You fools are the ones who are kanging my commit.. which I took the time find all those authors emails, put it together and everything I've already mentioned. As for the selinux policy you've linked, I solved that myself after encountering the error during build time so it's not a kang, lol?
> > > > 
> > > > 
> > > > Code refactor & Clean up, lol, I wonder how little thing you did comparing to original DeviceSettings. Anyone can do a comparation if they want.
> > > 
> > > 
> > > Whatever your stance is on how much I did, x, y and Z is irrelevant. I put the commit together, and it should be updated to reflect such.
> > 
> > 
> > Oh, if you saying so, who came to spam and call Chandu kanger while he is doing same squash thing?
> 
> Squashing isn't kanging. In fact, I have a list of commit to commit shit that Chandu picked from me, removed my signatures from and tried to pull it off to the community as if he found them himself, etc. It's pretty ironic you guys can't take accountability for anything but defend yourselves to no end despite being in the wrong.

Next time before you come, reflect what you have done. https://github.com/Evolution-X-Devices/device_oneplus_sm8250-common/commit/65357d7e21187d9298c2dacdebd14b0182c90ba9
Taken co-author in 4th place for what? Just a vendorsetup.sh which even a kang of others? And you can squash that sepolicy error into this, but you didn't, take yourself as a author.

**Comment by malfucntion** [comment]
https://github.com/malfucntion/device_oneplus_sdm845-common/commit/c5a9a91b60db9edb94a4453543dbf71c804878e5
